version: "3"

services:
    dummyproject-django:
        restart: always
        build:
            context: "./dummyproject/"
        environment:
            - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
            - "POSTGRES_DB=${POSTGRES_DB}"
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "APP_URL=${APP_URL}"
        command:
            "gunicorn dummyproject.wsgi --bind 0.0.0.0:8000"
        depends_on:
            - "dummyproject-db"
        expose:
            - "8000"

    dummyproject-caddy:
        restart: always
        image: "caddy:2-alpine"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - "APP_URL=${APP_URL}"
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"

    dummyproject-db:
        restart: always
        image: "postgres:15-alpine"
        expose:
            - "5432"
        environment:
            - "POSTGRES_DB=${POSTGRES_DB}"
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"

volumes:
    postgres_data:
